#!/usr/bin/env php
<?php

use Dotenv\Dotenv;

define('START_TIME', microtime(true));

// Enable handler
require_once(__DIR__.'/core/handler.php');

// Load Composer Packages
if(!is_file('/vendor/autoload.php')){
    require_once(__DIR__ . '/vendor/autoload.php');
}else{
    throw new Exception('composer not working');
}

// Load ENV values
if(!is_file('/.env')){
    Dotenv::createImmutable(__DIR__)->load();
}else{
    throw new Exception('.env file not found');
}

// Require Framework Core
require_once(__DIR__.'/core/core.php');

require_once('core/cli.php');

writeLn('');
writeLn('');
writeLn('----- Terminal start -----', ['bold', 'magentabg']);
writeLn('');

if (PHP_SAPI == "cli") {
    parse_str($argv[1], $arg);
    $option = $argv[1];
    //writeLn($argv[1], ['green']);

    if(!empty($option)){
        if(strpos($option, ':')){
            write('Command and Option: ');
            writeLn($option, ['green']);
            writeLn('');

            $options = explode(':', $option);
            $option = $options[0];
            $suboption = $options[1];

            switch($option){
                case 'cache':
                    
                    // Cache command
                    if($suboption == 'clear'){
                        $cache_path = realpath(__DIR__.'/storage/cache/views');
                        writeLn($cache_path);
                        (new File)->deleteDir($cache_path);
                        writeLn('Cache clear succesfully!');
                    }

                break;
            }

            //print_r($options);
        }else{
            write('Command: ');
            writeLn($option, ['green']);
            writeLn('');

            switch ($option){
                case 'serve':
                    $command = "php -S ".env('APP_SERVE', "127.0.0.1").":".env('APP_SERVE_PORT', 8000)." index.php";
                    shell_exec($command);
                break;
                case 'optimize':
                    shell_exec('php run cache:clear');
                    writeLn('Cache clear');
                break;
            }
        }
        
        
    }


    // Access argument values using getopt()
    //print_r($option);
} else {
    // Access argument values using $_GET etc. 
}

writeLn('');
writeLn('----- Terminal end session -----', ['bold', 'magentabg']);
writeLn('');
writeLn('');
?>